server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: business-microservice01-customer
          uri: lb://business-microservice01-customer
          predicates:
            - Path=/api/customer/**
        - id: business-microservice02-product
          uri: lb://business-microservice02-product
          predicates:
            - Path=/api/product/**            
        - id: business-microservice03-operation
          uri: lb://business-microservice03-operation
          predicates:
            - Path=/api/operationPassive/**
        - id: business-microservice04-location
          uri: lb://business-microservice04-location
          predicates:
            - Path=/api/business-microservice04-location/location/**  