server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: business-microservice00-master
          uri: lb://business-microservice00-master
          predicates:
            - Path=/api/business-microservice00-master/**      
        - id: business-microservice01-customer
          uri: lb://business-microservice01-customer
          predicates:
            - Path=/api/business-microservice01-customer/**
        - id: business-microservice02-product
          uri: lb://business-microservice02-product
          predicates:
            - Path=/api/business-microservice02-product/**
        - id: business-microservice03-operation
          uri: lb://business-microservice03-operation
          predicates:
            - Path=/api/business-microservice03-operation/**
        - id: business-microservice04-location
          uri: lb://business-microservice04-location
          predicates:
            - Path=/api/business-microservice04-location/**  
        - id: business-microservice0501-card
          uri: lb://business-microservice0501-card
          predicates:
            - Path=/api/business-microservice0501-card/**
        - id: business-microservice0502-card
          uri: lb://business-microservice0502-card
          predicates:
            - Path=/api/business-microservice0502-card/**
        - id: business-microservice06-purse
          uri: lb://business-microservice06-purse
          predicates:
            - Path=/api/business-microservice06-purse/**  
        - id: business-microservice07-bootcoin
          uri: lb://business-microservice07-bootcoin
          predicates:
            - Path=/api/business-microservice07-bootcoin/**            